export const workExperience = [
  {
    icon: "S",
    company: "StarBucks Landing Page",
    role: "React, TailwindCSS, Framer Motion",
    shortdesc: "Create topic specific communities or channels",
    desc: "People subscribe to your channels, becoming contributors and gaining value from real life experiences. Share more resources and profound ideas to grow your community.",
    bgColor: "bg-green-600",
    textColor: "text-white",
    sourceCode: "https://github.com/mayank2130/Grouple/tree/master",
    webLink: "https://starbucks-landing-page-beige.vercel.app/",
  },
  {
    icon: "C",
    company: "Sporting Bike Landing Page",
    role: "React, TailwindCSS, Framer Motion",
    shortdesc: "Create or join your friends in a chat room",
    desc: "Using websockets, this is a real time chat application that allows you to create private chat rooms.",
    bgColor: "bg-black",
    textColor: "text-white",
    sourceCode: "https://github.com/mayank2130/real-time-chat-app",
    webLink: "https://byclyle-frontend.vercel.app/",
  },
  {
    icon: "F",
    company: "Ferrari Landing Page",
    role: "React, TailwindCSS, Framer Motion",
    shortdesc: "Create or join your friends in a chat room",
    desc: "Using websockets, this is a real time chat application that allows you to create private chat rooms.",
    bgColor: "bg-red-600",
    textColor: "text-white",
    sourceCode: "https://github.com/mayank2130/real-time-chat-app",
    webLink: "https://ferrari-landing-page-theta.vercel.app/",
  },
  // {
  //   icon: "A",
  //   company: "Aptitude Testing",
  //   role: "Nextjs",
  //   shortdesc: "Create custom tests and take them with a progress record.",
  //   desc: "Practise spaced-repition perfectly by creating and answering questions with a high quality evalutation and feedback system, which helps you progress.",
  //   bgColor: "bg-red-600",
  //   textColor: "text-white",
  //   sourceCode: "https://github.com/mayank2130/Aptitude-test",
  //   webLink: "",
  // },
  // {
  //   icon: "B",
  //   company: "Business Empire Game",
  //   role: "React Native, EXPO, Async Storage",
  //   shortdesc: " Billionaire's Life Simulator",
  //   desc: "Ever wondered what it's like to live the life of a billionaire? In this game, you’ll grow your empire by buying businesses, collecting assets like cars, houses, and art pieces, and navigate the complexities of wealth and power!",
  //   bgColor: "bg-blue-600",
  //   textColor: "text-slate-100",
  //   sourceCode: "https://github.com/mayank2130/business-game",
  //   webLink: "",
  // },
  // {
  //   icon: "F",
  //   company: "FavProf",
  //   role: "Nextjs, React Native",
  //   shortdesc:
  //     "FavProf is an AI professor tailored to teach you about any topic.",
  //   desc: "Imagine an AI that provides you a roadmap, evaluates your tests, and changes difficulty levels based on your progress, you'll gain more knowledge about the subject than the degree could ever provide you with.",
  //   bgColor: "bg-purple-600",
  //   textColor: "text-white",
  //   sourceCode: "",
  //   webLink: "",
  // },

  // {
  //   icon: "M",
  //   company: "Personal Communities",
  //   role: "Nextjs",
  //   shortdesc: "Create topic specific communities or channels",
  //   desc: "People subscribe to your channels, becoming contributors and gaining value from real life experiences. Share more resources and profound ideas to grow your community.",
  //   bgColor: "bg-black",
  //   textColor: "text-white",
  //   sourceCode: "https://github.com/mayank2130/Grouple/tree/master",
  //   webLink: "",
  // },
];

export const greatWorkExp = [
  {
    icon: "GC",
    company: "Gmail Chat",
    role: "Anthropic API, LLM Tool Calling, LLM in Loop, Gmail Search API",
    shortdesc:
      "Using LLM tool calling and a complex designed architecture to extensive email search.",
    desc: "With tool calling and a complex architecture to put llms in loop for effectively searching emails and finding the right answer to the user query.",
    bgColor: "bg-black",
    textColor: "text-white",
    sourceCode: "https://github.com/mayank2130/",
    webLink: "",
  },
  {
    icon: "UI",
    company: "Mobile UI components library",
    role: "React Native, Next.js, tsup",
    shortdesc: "Build react native apps with 10x modern UI components.",
    desc: "Use this component library in your react native project by typeing the command  `npx @mayank2310/my-lib-ui add button`.",
    bgColor: "bg-black",
    textColor: "text-white",
    sourceCode: "https://github.com/mayank2130/tapit-ui",
    webLink: "https://tapui.vercel.app/",
  },
  {
    icon: "Vi",
    company: "Record Video with Loom Clone",
    role: "Nextjs, Electron js (Desktop App), AWS S3 Bucket",
    shortdesc: "A screen recorder desktop app with a dashboard.",
    desc: "This screen recorder app gives you the main features of loom and you can also view your recorded videos on your dashboard, share them to your clients and generate transcripts and summary of every upload to AWS.",
    bgColor: "bg-orange-600",
    textColor: "text-white",
    sourceCode: "https://github.com/mayank2130/Video-Share",
    webLink: "",
  },
  {
    icon: "U",
    company: "Uber Clone",
    role: "React Native, Google Maps, APIs",
    shortdesc: "Uber clone with it's complete functionality and also payments.",
    desc: "Using React Native, Google Places & directions API, react native maps and stripe payments a complete application.",
    bgColor: "bg-black",
    textColor: "text-white",
    sourceCode: "https://github.com/mayank2130/uber-clone",
    webLink: "",
  },
  {
    icon: "P",
    company: "Custom Phone Case",
    role: "Nextjs, AWS S3, CloudFront URL, Canvas edit layout ",
    shortdesc: "A customizable phone cover/case for Iphones.",
    desc: "Uploaded images are saved into AWS S3, a editing canvas for users to place their image on the phone case and pay using strip payments.",
    bgColor: "bg-green-500",
    textColor: "text-white",
    sourceCode: "https://github.com/mayank2130/cobracase-dev",
    webLink: "https://cobracase-dev.vercel.app/",
  },
];
