export const workExperience = [
    {
      icon: "F",
      company: "FavProf",
      role: "Nextjs, React Native",
      shortdesc:
        "FavProf is an AI professor tailored to teach you about any topic.",
      desc: "Imagine an AI that provides you a roadmap, evaluates your tests, and changes difficulty levels based on your progress, you'll gain more knowledge about the subject than the degree could ever provide you with.",
      bgColor: "bg-purple-600",
      textColor: "text-white",
      sourceCode: "",
      webLink: "",
    },
    {
      icon: "B",
      company: "Business Empire Game",
      role: "React Native, EXPO, Async Storage",
      shortdesc: " Billionaire's Life Simulator",
      desc: "Ever wondered what it's like to live the life of a billionaire? In this game, you’ll grow your empire by buying businesses, collecting assets like cars, houses, and art pieces, and navigate the complexities of wealth and power!",
      bgColor: "bg-green-500",
      textColor: "text-slate-100",
      sourceCode: "https://github.com/mayank2130/business-game",
      webLink: "",
    },
    {
      icon: "U",
      company: "Uber Clone",
      role: "React Native, Google Maps, APIs",
      shortdesc: "Uber clone with it's complete functionality and also payments.",
      desc: "Using React Native, Google Places & directions API, react native maps and stripe payments a complete application.",
      bgColor: "bg-black",
      textColor: "text-white",
      sourceCode: "https://github.com/mayank2130/uber-clone",
      webLink: "",
    },
    {
      icon: "C",
      company: "AI Business Chatbot",
      role: "Nextjs, OpenAI",
      shortdesc: "A customizable add-on chatbot for all websites.",
      desc: "The Chatbot has the entire context of the business, it answers queries of the visitors and helps them find the right product leading to a higher conversion rate.",
      bgColor: "bg-orange-600",
      textColor: "text-white",
      sourceCode: "https://github.com/mayank2130/sass-AI-chatbot",
      webLink: "",
    },
    {
      icon: "P",
      company: "Custom Phone Case",
      role: "Nextjs, AWS S3, CloudFront URL, Canvas edit layout ",
      shortdesc: "A customizable phone cover/case for Iphones.",
      desc: "Uploaded images are saved into AWS S3, a editing canvas for users to place their image on the phone case and pay using strip payments.",
      bgColor: "bg-green-500",
      textColor: "text-white",
      sourceCode: "https://github.com/mayank2130/cobracase-dev",
      webLink: "https://cobracase-dev.vercel.app/",
    },
    {
      icon: "A",
      company: "Aptitude Testing",
      role: "Nextjs",
      shortdesc: "Create custom tests and take them with a progress record.",
      desc: "Practise spaced-repition perfectly by creating and answering questions with a high quality evalutation and feedback system, which helps you progress.",
      bgColor: "bg-red-600",
      textColor: "text-white",
      sourceCode: "https://github.com/mayank2130/Aptitude-test",
      webLink: "",
    },
    {
      icon: "M",
      company: "Personal Communities",
      role: "Nextjs",
      shortdesc: "Create topic specific communities or channels",
      desc: "People subscribe to your channels, becoming contributors and gaining value from real life experiences. Share more resources and profound ideas to grow your community.",
      bgColor: "bg-black",
      textColor: "text-white",
      sourceCode: "https://github.com/mayank2130/Grouple",
      webLink: "",
    },
  ];